### ISSUE TITLE
Add tools

### ISSUE THREAD

**Issue by marcusradell** [jepz/read-challenge#2]
I'd recommend adding eslint, prettier, and eslint-config-prettier.

Also, if you want to skip the webpack part for now, run create-react-app on the project to get a good foundation.

**Comment by jepz** [comment]
added eslint, prettier, and eslint-config-prettier to package.json.

create-react-app was used when starting the app, so wepback should work.

**Comment by marcusradell** [comment]
Awesome work!

Welcome to the real world of open source :-D
